apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-worker
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
      role: worker
  template:
    metadata:
      labels:
        app: media
        role: worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: media-api
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: media-db-credentials
      containers:
        - name: media-worker
          image: acrdevmedia.azurecr.io/media-api:1.1.1
          command: ["python", "worker.py"]
          env:
            - name: AZURE_CLIENT_ID
              value: "2308ae95-bf08-486f-8dbe-56315fab638c"
            - name: REDIS_URL
              value: redis://redis.media.svc.cluster.local:6379/0
            - name: DB_HOST
              value: psql-dev-media-ne.postgres.database.azure.com
            - name: DB_USER
              value: uami-media-dev-ne
            - name: DB_NAME
              value: media
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true