apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Western-1/enterprise-aks-gitops.git
    targetRevision: main
    path: apps/media
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true